# Generated by Django 6.0.1 on 2026-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(related_name='tags', to='books.book'),
        ),
    ]
